services:
  tomenu:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/toomcis/tomenu:latest
    restart: unless-stopped
    container_name: tomenu-api
    environment:
      - PORT=2332
      - MAIN_DB=/app/data/main.db
      - NAMENU_DB=/app/data/namenu.db
    ports:
      - "2332:2332"
    volumes:
      - tomenu_data:/app/data   # persists both main.db and namenu.db
    tty: true
    stdin_open: true

volumes:
  tomenu_data: